### ISSUE TITLE
Add DNS Support - dyn.com

### ISSUE THREAD

**Issue by austinnichols101** [janeczku/rancher-letsencrypt#1]
What would be involved in adding support for an additional DNS provider?  Specifically, I would like to see support added the DYN Managed DNS platform.

API Reference: https://help.dyn.com/dns-api-knowledge-base/

**Comment by janeczku** [comment]
There is a pending PR for Dyn DNS in the upstream ACME library: https://github.com/xenolf/lego/pull/105
So once that landed we can integrate it here.

**Comment by austinnichols101** [comment]
FYI - just checked and PR was merged.

**Comment by janeczku** [comment]
Cool. I'll have a look.

**Comment by janeczku** [comment]
Dyn provider added in 46f12b3

**Comment by austinnichols101** [comment]
Thank you sir!

**Comment by austinnichols101** [comment]
@janeczku - is there a way to test this now, or do I need to wait for it to be merged into the community catalog?

**Comment by janeczku** [comment]
You can always build the app and the image using the Makefile and then run as normal service passing all necessary env vars. The community image will be updated within the next two days.
