### ISSUE TITLE
Error obtaining certificate

### ISSUE THREAD

**Issue by opb** [janeczku/rancher-letsencrypt#11]
Hi there

I've just se tup a new rancher deployment, and Am currently trying to ge this letsencrypt stack working.

I simply added from the catalog, filled in the details (I'm using DNSimple) and launched. The service keeps restarting, and by using the `docker logs` command, I see the following lines, repeated over and over:

```
level=info msg="Starting Let's Encrypt Certificate Manager v0.2.7 5dbb48c"
level=info msg="Using locally stored Let's Encrypt account for opb@redacted.com"
level=info msg="Trying to obtain SSL certificate for myhost.mydomain.uk"
level=error msg="[myhost.mydomain.uk] Error obtaining certificate: Error presenting token dns: domain must be fully qualified"
```

I was using a real domain which is already set up in DNSimple, but have obviously swapped it out for a placeholder there. 

Any suggestions would be appreciated, thanks!

**Comment by janeczku** [comment]
Hi, thanks for this report.
The error is due to a bug in the upstream ACME library. I just submitted a patch and as soon as that gets merged i will push a new image for Rancher.
https://github.com/xenolf/lego/pull/193

**Comment by opb** [comment]
Awesome, thanks for following up so quickly!

**Comment by janeczku** [comment]
@opb If you wanna give it a try before this makes it into the community catalog:
Clone or upgrade the letsencrypt service in Rancher and change the image to: rancher-letsencrypt:v0.2.8
