### ISSUE TITLE
Support for Rancher 2.0?

### ISSUE THREAD

**Issue by cloudlady911** [janeczku/rancher-letsencrypt#112]
Will there be support for this in Rancher 2.0?

**Comment by ghost** [comment]
I wouldn't bet on it, this project has not been under development for a long time.

Also just an FYI:
- Currently this catalog item utilizes a version of lego < 0.40 (https://github.com/xenolf/lego) which only supports acme v1, which will be deprecated at some point.

**Comment by alex-kovalchuk** [comment]
> which will be deprecated at some point

Already deprecated. :'(

**Comment by cloudlady911** [comment]
Closing this.
