### ISSUE TITLE
Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2

### ISSUE THREAD

**Issue by danibjor** [janeczku/rancher-letsencrypt#117]
Certificate renewal stopped working. Seems like they disabled the v1 api and code needs to be upgraded to support v2.

```
11.12.2019 10:09:03time="2019-12-11T09:09:03Z" level=fatal msg="LetsEncrypt client: Failed to register account: acme: Error 403 - urn:acme:error:unauthorized - Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details."
11.12.2019 10:09:05time="2019-12-11T09:09:05Z" level=info msg="Starting Let's Encrypt Certificate Manager v0.5.0 0913231"
11.12.2019 10:09:06time="2019-12-11T09:09:06Z" level=info msg="Creating Let's Encrypt account for myname@mydomain.com"
```

**Comment by hajnalmt** [comment]
Use https://hub.docker.com/r/vxcontrol/rancher-letsencrypt as a drop in replacement for the original. The old janecku image does not working anymore...

**Comment by netfet** [comment]
@hajnalmt  You made my day :D

**Comment by danibjor** [comment]
@hajnalmt thanks for the reply. Did some searching around docker hub on same day as I reported the issue, and also tested a few alternatives. Seems like the image https://hub.docker.com/r/uadevops/rancher-letsencrypt also works good. It's also more updated, last month, while vxcontrol's image is two years old.

**Comment by eldadfux** [comment]
@hajnalmt saved me so much work. viva la open-source 🎉
