### ISSUE TITLE
Fails on CloudFlare DNS

### ISSUE THREAD

**Issue by ColtonProvias** [janeczku/rancher-letsencrypt#12]
Just started having it fail to obtain certificates with CloudFlare DNS.

```
4/24/2016 1:54:14 PMlevel=info msg="Starting Let's Encrypt Certificate Manager v0.2.8 5d5d280"
4/24/2016 1:54:14 PMlevel=info msg="Using locally stored Let's Encrypt account for colton@*****"
4/24/2016 1:54:14 PMlevel=info msg="Trying to obtain SSL certificate for ..."
4/24/2016 1:57:22 PMlevel=error msg="[****] Error obtaining certificate: acme: Error 400 - urn:acme:error:malformed - Unable to update challenge :: Response does not complete challenge"
```

There was a recent change to crackcomm/cloudflare#4 that has broken compatibility with other Rancher Go-based components.  This may be the cause of the issue I'm seeing.

**Comment by janeczku** [comment]
Hi,  i could not reproduce this with rancher-letsencrypt v0.2.7. Do you see this error both with the sandbox and production API endpoints? Please check if there any stale records for `_acme-challenge.<certificate-domain>` in your Cloudflare DNS zone as this would definitely cause the validation to fail.

**Comment by janeczku** [comment]
I suspect that this might be due to intermittent spikes in CloudFlare DNS propagation times. See related issue here: https://github.com/xenolf/lego/issues/190

**Comment by EugenMayer** [comment]
works for me without issues

**Comment by janeczku** [comment]
Please reopen if you keep seeing that issue.
