### ISSUE TITLE
Upgrade community catalog

### ISSUE THREAD

**Issue by milovanderlinden** [janeczku/rancher-letsencrypt#13]
Hello janeczku, 

Thank you for your great work. Do you have an estimate when there will be an update for the community catalog? It is now at 0.2.7

**Comment by janeczku** [comment]
Hi @milovanderlinden, i will cut another release this week and then update the catalog with it. Anything in particular that doesn't work for you with the 0.2.7 release?

**Comment by milovanderlinden** [comment]
That would be great!

I particularly want to try name cheap. In 0.2.7 it is not yet available.
Op 18 mei 2016 00:14 schreef "Jan B" <notifications@github.com>:

**Comment by EugenMayer** [comment]
Same here, having a need for namecheap. Have to fork for now ;/

**Comment by EugenMayer** [comment]
@milovanderlinden i have created a working release here for now https://github.com/EugenMayer/kontextwork-catalog - i moved away from namecheap though since they do not open the API in general, just under conditions ( min of 20 Domains or 50$ account balance ). If you look for an alternative, cloudflare free does all you need for this

**Comment by milovanderlinden** [comment]
@EugenMayer thank you for the great insight! I will give cloudflare free a spin.

**Comment by janeczku** [comment]
@EugenMayer @milovanderlinden did one of you try out creating certificates via the Namecheap API using the catalog link Eugen posted? I am starting to think that it maybe not worth integrating them with all the restrictions they impose on using their API (plus the seemingly very long DNS propagation time)...

**Comment by EugenMayer** [comment]
well i would have tried, but it did not make sense out of the reasons you just named. Way to hard limits on the API, esp. compared to cloudflare, which is even free and very convenient, it seems to make no sense.

I have a "payed" account on namecheap for now, but it will be closed this week. Still i wont be able to test the API

**Comment by janeczku** [comment]
Thanks for the feedback, Eugen. Waiting on @milovanderlinden to confirm that he found a happier home for his DNS at CloudFlare 😀

**Comment by janeczku** [comment]
see https://github.com/rancher/community-catalog/pull/165
