### ISSUE TITLE
What happens on renewal [question]

### ISSUE THREAD

**Issue by riaan53** [janeczku/rancher-letsencrypt#24]
Hi,

Just a question on what happens when the certs are renewed and propagated to the load balancers. Will the load balancers restart or will all new connections just use the updated certs without any interruption? Im mainly using long running websocket connections.

Thank you :)

Regards,
Riaan

**Comment by InAnimaTe** [comment]
Additionally, what changes are upcoming for this? Between more DNS provider support, HTTP support, and the new 1.2.0 release with completely overhauled Load Balancer, it seems like this awesome service is ripe for some improvements.

From my quick testing, it still does work with Route53 well so grabbing and storing the certificate. But questions arise after 3mo expire on how the LB's get searched for and updated. Would love some more input and to help this project move forward. 

Between this and the new LB, we're at the cusp of an active SSL/TLS load balancing solution...just need to get a few things done ;)

**Comment by janeczku** [comment]
When the certificate is renewed the HAProxy based load balancer will be reload gracefully. While doing so in-flight requests should be served and not dropped. As far as websocket connections are concerned i have no idea really :)
