### ISSUE TITLE
Add Gandi DNS provider

### ISSUE THREAD

**Issue by samouds** [janeczku/rancher-letsencrypt#26]
Is there any plan to add Gandi as a DNS Provider ?

https://github.com/Gandi/letsencrypt-gandi
https://github.com/xenolf/lego/tree/master/providers/dns/gandi

Thanks !

**Comment by janeczku** [comment]
Hi @samouds, happy to accept the PR if you submit one. Adding a provider from lego is pretty straight forward.

**Comment by samouds** [comment]
Hi @janeczku, how can I do this ?

**Comment by samouds** [comment]
@janeczku I've forked the project to add Gandi : https://github.com/samouds/rancher-letsencrypt

Made some changes : 
- add Gandi to context.go and providers.go
- add github.com/xenolf/lego/providers/dns/gandi manually to deps (how to do it with godep ?)


But when I create the container on rancher I get this error : 

`06/08/2016 14:26:09level=fatal msg="LetsEncrypt client: Could not set DNS provider: Unsupported DNS provider: Gandi"`

**Comment by janeczku** [comment]
Added per https://github.com/janeczku/rancher-letsencrypt/commit/e1cf7dcdf4d41320d298d76c846c8d3d6268b01e
