### ISSUE TITLE
Introduce the simple HTTP challenge

### ISSUE THREAD

**Issue by davidknezic** [janeczku/rancher-letsencrypt#28]
I've been using [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) for a couple of months now and had a great experience. However, it doesn't really work nicely with the Rancher load balancer service.

This is why I've switched to `rancher-letsencrypt`, which is amazing too. However, it's unusable for all the services we deploy at work. This is because I don't have access to the DNS records for the domains.

Luckily, there's multiple challenges available in the ACME standard, one of which is the [simple HTTP challenge](https://letsencrypt.github.io/acme-spec/#rfc.section.7.1). This is how I've created certificates for our work domains using `jwilder/nginx-proxy`.

Now it would be great if `rancher-letsencrypt` had the option to use the HTTP-based challange instead of the DNS-based. Would that be possible?

**Comment by janeczku** [comment]
Hi @davidknezic great suggestion. That is definitely be possible. Wouldn't be as convenient as the DNS based challenge though, since you would have to make sure that your load balancer(s) route the challenge request to the lets-encrypt service.

**Comment by davidknezic** [comment]
Yes, the load balancer route would be an additional step compared to the DNS challenge. On the other side, this HTTP challenge could be used by people using yet unsupported DNS providers.

Would you be interested in making this part of `rancher-letsencrypt`? If so, I'd try to create a pull request.

**Comment by CrystalMethod** [comment]
👍

**Comment by ccatlett2000** [comment]
If this would be possible, that would be excellent. I can't use rancher with letsencrypt as I host my own DNS (And it appears there is no bind provider) and there is no HTTP challenge support.

**Comment by davidknezic** [comment]
I had a look at the implementation two weeks ago and it didn't seem to complex to implement.

The [`xenolf/lego`](https://github.com/xenolf/lego) library which is a dependency of `rancher-letsencrypt` and implements all the DNS challenges, has an [implementation for the HTTP challenge](https://github.com/xenolf/lego/blob/master/providers/http/webroot/webroot.go) too. I think it's a matter of integrating that challenge, adding the HTTP challenge to the providers dropdown and starting a web server to serve the generated challenge files.

However, currently I'm on vacation and will only have time to work on this in two weeks again.

**Comment by ccatlett2000** [comment]
I'll look into it, but my go skills are somewhat rusty. Also, it appears the project's maintainer had been inactive for almost a month, so I don't know if he'll accept a pull request.

**Comment by janeczku** [comment]
Hi guys, sorry for my absence here. I have been busy with other projects. I'll happily accept a PR for this and plan to cut a new release in the middle of september!

**Comment by ccatlett2000** [comment]
I'll see if I can figure out how to get HTTP challenges to work then.

**Comment by davidknezic** [comment]
@ccatlett2000 go is hard, I can totally confirm that 😄 

But I managed to set up the project, extend it and build and test the docker image. There's still a bug somewhere that I'll try to get rid of before I push my work sometime next week.

**Comment by UFOMelkor** [comment]
Anything new about it? :blush:

**Comment by johanndt** [comment]
Bump! Anything @davidknezic ? Happy to contribute or help testing.

**Comment by davidknezic** [comment]
Hi all, I managed to renew all my certs in last minute before they expired 😄.
The code changes are pushed, you can find them in #39.

**Comment by johanndt** [comment]
Awesome @davidknezic I'll give it a test today. :-)

**Comment by johanndt** [comment]
So @davidknezic - what is the easiest way to try this without it being in the community catalog yet? Just build the dockerfile and launch it? I'm not sure which env vars to set etc.

**Comment by johanndt** [comment]
Hi @davidknezic - I've used it on one of our staging/testing systems today and seems to work okay so far.

**Comment by johanndt** [comment]
I keep noticing this line in the container logs:
`Debug mode: Forced certificate renewal in 120 seconds`

So it starts hitting the API rate limits pretty quickly. I tried to look through the repo and configs but couldn't see anything to turn this off or override it.

**Comment by davidknezic** [comment]
> I've used it on one of our staging/testing systems today and seems to work okay so far.

Great! I'm now running multiple instances and all my certs are nicely being kept a 3 months expiration date.

> I keep noticing this line in the container logs:
> `Debug mode: Forced certificate renewal in 120 seconds`

I just noticed that I built the image using the `Dockerfile.dev` file instead of `Dockerfile`. That's why our containers get started in debug mode, where it renews the certs every 120s, exceeding the rate limit after a while.

There's a new image without the debug mode, which will follow your `RENEWAL_TIME` option.

`davidknezic/rancher-letsencrypt:dev-a13546f`

For me it fails to start, because of the exceeded rate limit, so I'll give it a try tomorrow.

**Comment by johanndt** [comment]
Thanks David. I've updated the container, but I also have to wait for a while for the limit to expire. But I'm sure it will be fine. All looks good.

I have to say that setting it up was a bit of a catch-22 situation, but I'm not sure what can be done. The load-balancer I was using needed the certificate, but it wasn't created yet. And starting the letsencrypt container couldn't create the certificate until the load balancer was up to accept the http challenge (obviously).

So I had to create a one-time lb for the first certificate creation, and then restart it with the new cert as well as the proper https website forwarding rules set up.

It wasn't hard and it's probably because I had an existing load-balancer I wanted to keep. Just saying that if folks wanted to switch their existing production system to letsencrypt it will probably take a short outage, or some shuffling around of loadbalancers on separate hosts... I'm not sure.

Still I'm very happy to have this solution now! Thanks for taking the time and working on it. 😄

**Comment by johanndt** [comment]
So it's been a month... just wanted to report that @davidknezic 's container has been working for me without any issues. This should really get merged into master.

```
11/14/2016 2:36:15 PM[34mINFO[0m[0000] Starting Let's Encrypt Certificate Manager v0.4.0 45bb466 
11/14/2016 2:36:15 PM[34mINFO[0m[0000] Using locally stored Let's Encrypt account for redacted@redacted 
11/14/2016 2:36:15 PM[34mINFO[0m[0000] Found existing certificate 'StagingLetsEncrypt' in Rancher 
11/14/2016 2:36:15 PM[34mINFO[0m[0000] Trying to obtain SSL certificate (staging.mydomain.com) from Let's Encrypt CA 
11/14/2016 2:36:16 PM[34mINFO[0m[0001] Certificate saved to '/etc/letsencrypt/production/certs/StagingLetsEncrypt/fullchain.pem' 
11/14/2016 2:36:16 PM[34mINFO[0m[0001] Private key saved to '/etc/letsencrypt/production/certs/StagingLetsEncrypt/privkey.pem' 
11/14/2016 2:36:16 PM[34mINFO[0m[0001] Certificate obtained successfully            
11/14/2016 2:36:16 PM[34mINFO[0m[0001] Updated Rancher certificate 'StagingLetsEncrypt'
11/14/2016 2:36:33 PM[34mINFO[0m[0018] Upgraded load balancer 'staging-lb' with renewed certificate
11/14/2016 2:36:33 PM[34mINFO[0m[0018] Certificate renewal scheduled for 2017/01/29 05:00 UTC
```

**Comment by franciscocpg** [comment]
It's working for me too.

**Comment by ffittschen** [comment]
@franciscocpg @johanndt Did you extend the `rancher-compose.yml` with a path to the webroot? I'm currently trying to get this working manually until the PR is merged, but I'm wondering how to specify the path, that should be used by lego

**Comment by davidknezic** [comment]
@ffittschen glad this worked, I've added a couple of lines to the README based on your comment, hopefully making it clearer on how to use the HTTP challenge.
