### ISSUE TITLE
volume issues

### ISSUE THREAD

**Issue by ict4ngo** [janeczku/rancher-letsencrypt#29]
I just created a a new letsencrypt using the catalog, this is the configuration : 

> letsencrypt:
>   environment:
>     API_VERSION: Production
>     AWS_ACCESS_KEY: ''
>     AWS_SECRET_KEY: ''
>     CERT_NAME: *******************
>     CLOUDFLARE_EMAIL: ***************************
>     CLOUDFLARE_KEY: ****************************************
>     DNSIMPLE_EMAIL: ''
>     DNSIMPLE_KEY: ''
>     DOMAINS: *****************************
>     DO_ACCESS_TOKEN: ''
>     DYN_CUSTOMER_NAME: ''
>     DYN_PASSWORD: ''
>     DYN_USER_NAME: ''
>     EMAIL: *****************
>     EULA: 'Yes'
>     PROVIDER: CloudFlare
>     PUBLIC_KEY_TYPE: RSA-4096
>     RENEWAL_TIME: '12'
>   labels:
>     io.rancher.container.create_agent: 'true'
>     io.rancher.container.agent.role: environment
>   image: janeczku/rancher-letsencrypt:v0.3.0
>   volumes:
>   - /srv/docker/letsencrypt/production/certs:/etc/letsencrypt/production/certs
> 

The problem is if I go in /srv/docker/letsencrypt/production/certs it's empty.

Note:  I can still use the one for the rancher LB

**Comment by ict4ngo** [comment]
forget that the issue is https://github.com/janeczku/rancher-letsencrypt/issues/27

**Comment by janeczku** [comment]
Hi @ict4ngo, can you paste the log output for the service?

**Comment by janeczku** [comment]
@ict4ngo I understand that the certificate isn't created because of #27? Let's close this then.
