### ISSUE TITLE
Anti Replay nonce error in Production mode

### ISSUE THREAD

**Issue by guruvan** [janeczku/rancher-letsencrypt#3]
Trying to obtain a cert with the latest catalog version I'm unable to obtain a cert. 

See some issues floating around as late as the last couple weeks that letsencrypt may have an issue (a note in 3rd week Jan, tought they had it fixed, note from last week suggests other users (of letsencrypt clients) are having this issue. 

If you have a minute could you look into this? I'd really like to deploy a production service using rancher-letsencrypt (have one ready to go, production mode has it stopped) 

Thanks!!!

**Comment by janeczku** [comment]
@guruvan Interesting... I haven't seen this error before but judging from my interweb search this seems to be a thing recently. Seeing that i can't reproduce this, could you paste the log line with the error? THX

**Comment by janeczku** [comment]
Upstream issue: https://github.com/letsencrypt/boulder/issues/1217

**Comment by guruvan** [comment]
Thanks :) - I've seen this issue, and there's another mention https://community.letsencrypt.org/t/client-sent-an-unacceptable-anti-replay-nonce/11973 
`
This is using RT53 DNS. rancher-letsencrypt is running on AWS instance. 
 There's no trouble at all in obtaining the Sandbox certs. 

3/26/2016 10:26:14 AMlevel=info msg="Starting Let's Encrypt Certificate Manager v0.2.5 3e90d5f"
3/26/2016 10:26:15 AMlevel=info msg="Using locally stored Let's Encrypt account for guruvan@maza.club"
3/26/2016 10:26:15 AMlevel=debug msg="Looking up certificate by name [LE] electrum001.maza.club"
3/26/2016 10:26:15 AMlevel=info msg="Trying to obtain SSL certificate for electrum001.maza.club"
3/26/2016 10:26:15 AM[INFO][electrum001.maza.club] acme: Obtaining bundled SAN certificate
3/26/2016 10:26:15 AMlevel=error msg="[electrum001.maza.club] Failed to obtain certificate: acme: Error 400 - urn:acme:error:badNonce - JWS has invalid anti-replay nonce 8UlaNILJJQDr-LjFPWlu4C35Q5drR-S97-CSei0rxqQ"
3/26/2016 10:26:17 AMlevel=info msg="Starting Let's Encrypt Certificate Manager v0.2.5 3e90d5f"
3/26/2016 10:26:18 AMlevel=info msg="Using locally stored Let's Encrypt account for guruvan@maza.club"
3/26/2016 10:26:18 AMlevel=debug msg="Looking up certificate by name [LE] electrum001.maza.club"
3/26/2016 10:26:18 AMlevel=info msg="Trying to obtain SSL certificate for electrum001.maza.club"
3/26/2016 10:26:18 AM[INFO][electrum001.maza.club] acme: Obtaining bundled SAN certificate
3/26/2016 10:26:18 AMlevel=error msg="[electrum001.maza.club] Failed to obtain certificate: acme: Error 400 - urn:acme:error:badNonce - JWS has invalid anti-replay nonce mLQMOUJaAcAULrPufg26JY6hJpbaIxZrYirtgb6bg5E"`

**Comment by guruvan** [comment]
@janeczku - this may be simple operator error + bunk error message from letsencrypt. It looks like I may be denied because the email address above already has an account, and rancher-letsencrypt is trying to make a fresh account  - it maybe that it's less than clear in the rancher-letsencrypt docs that ops need to feed it their private key, or use a fresh email address for each cert collection. 

I'll make another few certs and verify this is correct.

While here, I'm wondering if this message 
`3/26/2016 11:03:24 AMlevel=debug msg="Test mode enabled: Certificate renewal in 120 seconds"`
is misconfiguration on my part, or normal? 120seconds seems a short time to renew the cert?

`3/26/2016 10:56:27 AMlevel=info msg="Starting Let's Encrypt Certificate Manager v0.2.5 3e90d5f"
3/26/2016 10:56:27 AMlevel=info msg="Generating private key (2048) for account electrum-ssl@guruvan.net."
3/26/2016 10:56:28 AMlevel=info msg="Creating Let's Encrypt account for electrum-ssl@guruvan.net"
3/26/2016 10:56:28 AM2016/03/26 17:56:28 [INFO] acme: Registering account for electrum-ssl@guruvan.net
3/26/2016 10:56:28 AMlevel=debug msg="Looking up certificate by name [LE] electrum002.maza.club"
3/26/2016 10:56:28 AMlevel=info msg="Trying to obtain SSL certificate for electrum002.maza.club"
3/26/2016 10:56:28 AM[INFO][electrum002.maza.club] acme: Obtaining bundled SAN certificate
3/26/2016 10:56:28 AM[INFO][electrum002.maza.club] acme: Could not find solver for: http-01
3/26/2016 10:56:28 AM[INFO][electrum002.maza.club] acme: Trying to solve DNS-01
3/26/2016 10:56:56 AM[INFO][electrum002.maza.club] Checking DNS record propagation...
3/26/2016 10:56:58 AM[INFO][electrum002.maza.club] The server validated our request
3/26/2016 10:57:26 AM[INFO][electrum002.maza.club] acme: Validations succeeded; requesting certificates
3/26/2016 10:57:27 AM[INFO] acme: Requesting issuer cert from https://acme-v01.api.letsencrypt.org/acme/issuer-cert
3/26/2016 10:57:27 AM[INFO][electrum002.maza.club] Server responded with a certificate.
3/26/2016 10:57:27 AMlevel=info msg="Successfully obtained certificate"
3/26/2016 10:57:27 AMlevel=debug msg="Added certificate: [LE] electrum002.maza.club"
3/26/2016 10:57:27 AMlevel=info msg="Added Rancher certificate resource: [LE] electrum002.maza.club"
3/26/2016 10:57:27 AMlevel=debug msg="Test mode enabled: Certificate renewal in 120 seconds"
3/26/2016 10:57:27 AMlevel=info msg="Next certificate renewal scheduled for 2016/06/10 12:00 UTC"`

**Comment by janeczku** [comment]
> While here, I'm wondering if this message 
3/26/2016 11:03:24 AMlevel=debug msg="Test mode enabled: Certificate renewal in 120 seconds"

This test mode is automatically enabled if you enable the **undocumented** debug mode via the environment variable :smile: 

>  it maybe that it's less than clear in the rancher-letsencrypt docs that ops need to feed it their private key, or use a fresh email address for each cert collection.

I don't think that's the way it works. I have been using the same email address repeatedly on different systems each time using a newly generated private key. Never bonked on me. Unless this is something they recently changed...

From your last log it seems that it working now for you?

**Comment by guruvan** [comment]
Yep - working - turned off the debug mode, and seems to work perfectly now :) 

Very handy tool!
