### ISSUE TITLE
Can´t obtain certifiate using cloudflare

### ISSUE THREAD

**Issue by wolli-lenzen** [janeczku/rancher-letsencrypt#30]
I installed the letsenrypt service from the rancher catalog and did all the nessecary configuration. On startup, I get the following errormessage in the service:

Error obtaining certificate: Error presenting token: invalid character '<' looking for beginning of value"

I´ve entered my domain, that is registered and active in cloudflare and additionaly a subdomain and I get the errormessage for both domain names.

**Comment by epleterte** [comment]
If you go into your Let'sEncrypt stack and click the "Compose YAML" button and then paste your config here it'll be much easier to help you. Make sure you remove credentials before posting! :)

**Comment by wolli-lenzen** [comment]
Meanwhile I found out, that the problem is Domain related. If I setup the service for another domain, it works fine, so it seem snot to be an issue of the rancher service, but an issue in domain configuration.

**Comment by wolli-lenzen** [comment]
It´s really strange. I have an external system with some other domain where the service runs without problem. 

Now I setup a new system, trying to obtain new certificates for different domains, but none of them ist working (with the same compose.yml) that looks like this:

ssl-exram:
  environment:
    API_VERSION: Production
    CERT_NAME: exram.de
    CLOUDFLARE_EMAIL: wl@exram.de
    CLOUDFLARE_KEY: xxxxxxxx
    DOMAINS: exram.de, www.exram.de
    EMAIL: wl@exram.de
    EULA: 'Yes'
    PROVIDER: CloudFlare
    PUBLIC_KEY_TYPE: RSA-2048
    RENEWAL_TIME: '12'
  log_driver: syslog
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  log_opt:
    syslog-address: udp://logs2.papertrailapp.com:xxxxx
    tag: ssl-exram
  image: janeczku/rancher-letsencrypt:v0.3.0
  volumes:
  - /etc/letsencrypt/production/certs

**Comment by wolli-lenzen** [comment]
One more information: 

If I take my not working config and deploy it on another datacenter with some other external IP but the same rancher infrastructure, the service works perfectly. So the service-config must be correct and also cloudflare account must be working correctly. 

I´m really confused about this. 

Also I have searched for the error message 
msg="[taxikomm.net] Error obtaining certificate: Error presenting token: invalid character '<' looking for beginning of value"

It looks like some error in parsing a HTTP Response where JSON is expected

**Comment by janeczku** [comment]
Most problems with Cloudflare should be fixed in the new version v0.4.0. Please update your service and reopen this ticket in case the issues persist. Thank you!
