### ISSUE TITLE
Add Support for namecheap

### ISSUE THREAD

**Issue by HazCod** [janeczku/rancher-letsencrypt#32]
Would be awesome if someone could implement namecheap support!

https://www.namecheap.com/support/api/intro.aspx

**Comment by RotemEmergi** [comment]
Any update on that ? I see that in 3.0 there is namecheap but it's not working  .

**Comment by RotemEmergi** [comment]
still no answer to this.

**Comment by janeczku** [comment]
Namecheap will not be supported in the near future since their slow DNS propagation doesn't play well with ACME domain validation.
