### ISSUE TITLE
Unsupported DNS provider

### ISSUE THREAD

**Issue by RotemEmergi** [janeczku/rancher-letsencrypt#34]
Hello , 

I am using rancher v1.1.3  and docker v1.8 .
I tried to configure your producat to work with Namecheap and get the error:
level=info msg="Starting Let's Encrypt Certificate Manager v0.3.0 f8965f6"
level=info msg="Generating private key (2048) for xxxx@xxxx.com."
level=info msg="Creating Let's Encrypt account for xxxxx@xxxxx.com"
level=fatal msg="LetsEncrypt client: Could not set DNS provider: Unsupported DNS provider: Namecheap"

Best Regards

**Comment by RotemEmergi** [comment]
still no answer to this.

**Comment by janeczku** [comment]
@RotemEmergi Namecheap support has been dropped. The new template soon to be released in the catalog should reflect this. Thanks!
