### ISSUE TITLE
I don't get a cert.pem 

### ISSUE THREAD

**Issue by gitlab-pano** [janeczku/rancher-letsencrypt#35]
After setting up Let's encrypt with the options to save to a folder, the certificate is generated and seems to work with NGINX. However the files that are generated and placed in the certs folder are: 
- fullchain.pem
- metadata.json
- privkey.pem

I expected that there would be a domain.crt file as well that contains the actual domain certificate.  Am I missing something?  I would like to use the certificates for a server that is outside of rancher.

**Comment by gitlab-pano** [comment]
According to documentation I should see:
cert.pem
chain.pem
fullchain.pem
privkey.pem

**Comment by gitlab-pano** [comment]
still no answer to this.

**Comment by janeczku** [comment]
`fullchain.pem` contains the actual domain certificate plus the intermediate certificate. Use in Nginx like this: 

```
ssl_certificate      /etc/letsencrypt/production/<CERTIFICATE-NAME>/fullchain.pem;
ssl_certificate_key  /etc/letsencrypt/production/<CERTIFICATE-NAME>/privkey.pem;
```

**Comment by radeno** [comment]
@janeczku without chain.pem and cert.pem you cannot use OCSP stapling effectivetelly. it helps 30% performance increase with ssl hand-shaking.
