### ISSUE TITLE
UDP connection refused

### ISSUE THREAD

**Issue by legoheld** [janeczku/rancher-letsencrypt#38]
Hi,

I have an issue when creating a new certificate with dnsimple. It looks like the connection to dnsimple was successful. The TXT record was created.
But after that the connection _to_ or _from_ rancher is not working.
Do I have to publish the 53 DNS port of rancher. Or can you give me a hint whats wrong in my setup?

Here is my log output:

```
10/5/2016 1:36:26 PMlevel=info msg="Starting Let's Encrypt Certificate Manager v0.3.0 f8965f6"
10/5/2016 1:36:26 PMlevel=info msg="Using locally stored Let's Encrypt account for **@**"
10/5/2016 1:36:26 PMlevel=info msg="Trying to obtain SSL certificate (my.domain.com) from Let's Encrypt CA"
10/5/2016 1:37:31 PMlevel=error msg="[my.domain.com] Error obtaining certificate: Time limit exceeded. Last error: read udp 172.17.0.3:39687->83.222.134.149:53: read: connection refused"
```

The ip 83.222.134.149 has only a rancher-agent running not the server.
And there is no public 53 port on 83.222.134.149. 

Rancher Server 1.1.4
Let's Encrypt 3.0.0

Maybe someone has a hint for me.
Thank you.

**Comment by janeczku** [comment]
Hi @legoheld please try with the new version of the template (v0.4.0) and reopen this ticket if this is still an issue for you. Thanks!

**Comment by proligde** [comment]
Same here - we're using a server where the network admins seem to have blocked outbound udp traffic while port 53 tcp work perfectly well.
