### ISSUE TITLE
Make the DNS provider optionnal [Proposal]

### ISSUE THREAD

**Issue by Dremor** [janeczku/rancher-letsencrypt#42]
I tried to use your letsencrypt stack. but I ran into a problem : I don't use one of the supported DNS provider.

But sending the certificate to the provider is only useful if the DNS provider provide a reverse-proxy services (like Cloudflare), and thus should be optional, allowing the user to use the stack more easily.

Would it be possible?

**Comment by janeczku** [comment]
Support for HTTP challenge has been added in https://github.com/janeczku/rancher-letsencrypt/commit/2777fcd8eb15fed992a01d41387d2904e010e501
