### ISSUE TITLE
Could not connect to Rancher API: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by natami** [janeczku/rancher-letsencrypt#43]
How do i setup letsencrypt to accept my self signed cert to connect to Rancher API?

12/11/2016 18.08.22level=info msg="Starting Let's Encrypt Certificate Manager v0.3.0 f8965f6"
12/11/2016 18.08.37level=fatal msg="Could not connect to Rancher API: Get https://xxxxxxx: x509: certificate signed by unknown authority"

**Comment by janeczku** [comment]
You would have to create your own letsencrypt image and add your self-signed certificate to the OS trust store, e.g.:

```
FROM janeczku/rancher-letsencrypt:latest
ADD <selfsigned-certificate.pem> /usr/local/share/ca-certificates/
RUN update-ca-certificates
```
