### ISSUE TITLE
What's the purpose of dns providers ?

### ISSUE THREAD

**Issue by Cygnust** [janeczku/rancher-letsencrypt#45]
Hi,
first thanks a lot for this module.

Sorry for the noob question but what's the purpose of using DNS providers ?
let's encrypt as itself doesn't use it if I don't get wrong ?

I want to know the way it works because my dns provider is ovh but my dns zone is managed by a private server.

Many thanks !

**Comment by msumpter** [comment]
Let's encrypt offers two ways to authenticate control over a domain requesting a certificate. One method is via an HTTP request and the other is via a DNS record. There is a dynamic string that needs to be found by the Let's encrypt servers to complete verification and sign your signing request.

This addon does the verification with DNS records and therefore needs access to dynamically insert records.

**Comment by janeczku** [comment]
@Cygnust With v0.4.0 you don't need to use a DNS provider for domain validation. Just choose the HTTP method instead. See the README for more information.
