### ISSUE TITLE
Fix/Remove Load Balancer Update

### ISSUE THREAD

**Issue by InAnimaTe** [janeczku/rancher-letsencrypt#49]
Using the new 1.2.0 release, I've been doing some testing with this service and I've found the following:

1. Interaction with the Certificate Store still works perfectly.
2. Looking for Load Balancers does not work and doesn't have to anymore. The new LB automatically sees something changes and updates (see below).

Log from replacing a self-signed I loaded up with one day remaining.

```
12/13/2016 5:20:00 PMlevel=info msg="Starting Let's Encrypt Certificate Manager v0.3.0 f8965f6"
12/13/2016 5:20:00 PMlevel=info msg="Using locally stored Let's Encrypt account for user@email.com"
12/13/2016 5:20:00 PMlevel=info msg="Found locally stored certificate 'cake'"
12/13/2016 5:20:00 PMlevel=info msg="Found existing certificate 'cake' in Rancher"
12/13/2016 5:20:00 PMlevel=info msg="Serial number mismatch between Rancher and local certificate 'pypi'"
12/13/2016 5:20:01 PMlevel=info msg="Updated Rancher certificate 'cake'"
12/13/2016 5:20:01 PMlevel=info msg="Certificate is not being used by any load balancer"
12/13/2016 5:20:01 PMlevel=info msg="Certificate renewal scheduled for 2017/02/19 12:00 UTC"
```

From Vincent in IRC:

```
yes the new balancer reads metadata and sees something changes, so the letsencrypt template doesn't need to try and do that anymore
```

Additonally, I'd appreciate a bit more information in the log lines around things like using the sandbox server etc.. i.e. 

```
Trying to obtain SSL certificate (domain.com) from Let's Encrypt CA Sandbox server
```

**Comment by janeczku** [comment]
@InAnimaTe [v0.4.0 ](https://github.com/janeczku/rancher-letsencrypt/releases/tag/v0.4.0) fixes load balancer updates on Rancher v1.2.0+. Even with the new LB implementation it's still necessary to actively trigger a lb update in the API after renewing the certificate.
I updated the log output to include information about the API version being used.
