### ISSUE TITLE
How often/when are certificates renewed?

### ISSUE THREAD

**Issue by krstffr** [janeczku/rancher-letsencrypt#53]
It says in the Rancher UI (and also got an email from Let's encrypt about it 10 days ago) that my certifcate will expire in 12 days, so my question is: how often are the certs renewed? Do I have to manually do something or will the renewal only run in like the last 3 days or something?

**Comment by B-Stefan** [comment]
I have the same question :)

**Comment by krstffr** [comment]
(@B-Stefan OK my cert has updated now, don't know when exactly but it's updated!)

Would still like an answer as to how often renewals occurs though! :)

**Comment by janeczku** [comment]
Certificates should be renewed 20 days before expiration in the soon to be released v0.4.0. Please reopen if you still receive these emails from Let's Encrypt after upgrading.
