### ISSUE TITLE
Ovh configuration from rancher catalog version

### ISSUE THREAD

**Issue by mroberty8** [janeczku/rancher-letsencrypt#55]
Hi,

When we install this container from rancher catalog, it's not possible to set env vars or setup needed config from GUI. Is it missing or i have missed something ?

Thx in advance.

**Comment by zaggash** [comment]
It seems, the template is not updated on the Rancher community side.
We can create our own to fix this missing part temporarily

**Comment by zaggash** [comment]
#17

**Comment by janeczku** [comment]
New template will be merged to the catalog shortly: https://github.com/rancher/community-catalog/pull/410
