### ISSUE TITLE
Failed to get cert with DigitalOcean

### ISSUE THREAD

**Issue by jstdoit** [janeczku/rancher-letsencrypt#58]
hi, i'm using digitalocean dns provider, after offering newly-generated token from digitalocean.com, i got error logs from rancher: 
`Error presenting token: HTTP 403: forbidden: You do not have access for the attempted action`

Is there any help? Thanks!

**Comment by janeczku** [comment]
@jstdoit Check your API key - does it have write permissions?

**Comment by jstdoit** [comment]
I'm not using DO anymore since then, thanks.
