### ISSUE TITLE
Volume size required

### ISSUE THREAD

**Issue by Treenity** [janeczku/rancher-letsencrypt#62]
After upgraded to v0.4.0 and tryed to use rancher-ebs storage, i got this error message : 
>  Upgrading (Failed to allocate instance [container:1i8153]: Bad instance [container:1i8153] in state [error]: Error response from daemon: create letsencrypt_lets-encrypt_2bf09: VolumeDriver.Create: size is required)

Is there a way to pass a volumedriver option, or maybe target a already existing volume?

**Comment by janeczku** [comment]
You would have to create your own letsencrypt image and add your self-signed certificate to the OS trust store, e.g.:

```
FROM janeczku/rancher-letsencrypt:latest
ADD <selfsigned-certificate.pem> /usr/local/share/ca-certificates/
RUN update-ca-certificates
```

**Comment by janeczku** [comment]
@Treenity I have updated the template with support for specifying the EBS volume size. PR here: https://github.com/rancher/community-catalog/pull/420

Let me know if this solves the issue for you.

**Comment by janeczku** [comment]
Closing as the latest template has been verified to work with rancher-ebs.
