### ISSUE TITLE
Support for run-once restart policy

### ISSUE THREAD

**Issue by proligde** [janeczku/rancher-letsencrypt#64]
I'm wondering it there might already be a way to prevent this container from running after issuing a cert and instead call it as a "run once" container. Due to memory consumption when running a lot of these containers I'd prefer to call them using a cron like https://hub.docker.com/r/socialengine/rancher-cron/ 

In combination of a fixed issue #50 this would be a perfect solution.

**Comment by janeczku** [comment]
@proligde That's a great idea. We just need to add a run once mode to the service and the `io.rancher.container.start_once` label to the catalog template.

**Comment by janeczku** [comment]
Implemented run once mode in https://github.com/janeczku/rancher-letsencrypt/commit/0e3694892af702f145b759baa1ac8a01c57271cd
