### ISSUE TITLE
HTTP challenge failing

### ISSUE THREAD

**Issue by vkruoso** [janeczku/rancher-letsencrypt#66]
I'm having issues trying to use the HTTP challenge mode of this image. I've correctly redirected the path to the container as instructed. Here is the relevant config piece of the haproxy controlling the domain:

``acl 22001_well_known__path path_beg -i /.well-known/``
``use_backend 22001_well_known_ if 22001_well_known__path``

Here is some of the logs:

```
Starting Let's Encrypt Certificate Manager v0.4.0 3c41d73
Using locally stored Let's Encrypt account for e...@l...i.com.br
Using Let's Encrypt Production API
Using HTTP challenge: Sleeping for 120 seconds before requesting certificate
Make sure that HTTP requests for '/.well-known/acme-challenge' for all certificate domains are forwarded to the container running this application
Trying to obtain SSL certificate (mydomain.com) from Let's Encrypt Production CA"
[mydomain.com] Error obtaining certificate: acme: Error 403 - urn:acme:error:unauthorized - The key authorization file from the server did not match this challenge [xBJZu1pLKkaCSLTg-O2E8a_mS3XMyNAdaFSTGQHAcfw.cQGmqsZCZMyiQjjJxniL6AgJoRGWEVzfbxTMa19TppE] != [TEST]\nError Detail:\n\tValidation for mydomain.com:80\n\tResolved to:\n\t\t104.xxx.8.209\n\tUsed: 104.xxx.8.209\n\n"
```

I can see the log from haproxy assuring the request was served:

```
Feb 25 19:49:49 localhost haproxy[22096]: 192.168.255.1:34146 [25/Feb/2017:19:49
:49.161] 22001 22001_well_known_/fa2a8e490bbbe366052aeba9e597ede4a1c1c3ba 0/0/0/
0/0 200 120 - - ---- 0/0/0/0/0 0/0 "GET /.well-known/acme-challenge/3AyIyN7_jc5C
eRNYP_XHvKYdKuzOslIQiqtgNwrFExc HTTP/1.0"
```

How can I further debug the process to make sure where the problem is?

**Comment by janeczku** [comment]
Might have to do with the host header not being correctly set by haproxy: https://github.com/xenolf/lego/issues/314#issuecomment-259360763
https://github.com/janeczku/rancher-letsencrypt/commit/8d2f8c7fdda706af71a7c9d79635698159857a31 should make this kind of issue surface in the logs.

**Comment by vkruoso** [comment]
Awesome! Got it working now. The new log message was a very clear in pointing that the host cloud be a problem, and fixing it enabled the certificate generation.
