### ISSUE TITLE
Support for azure dns

### ISSUE THREAD

**Issue by Flowman** [janeczku/rancher-letsencrypt#7]
Can we get support for azure dns?

https://azure.microsoft.com/en-us/services/dns/

**Comment by janeczku** [comment]
Tracking https://github.com/xenolf/lego/issues/180

**Comment by yobasystems** [comment]
+1 for this also integration with Namecheap would be great :)

**Comment by janeczku** [comment]
@yobasystems Namecheap will be integrated in the coming days.

**Comment by janeczku** [comment]
@yobasystems FYI, support for Namecheap was added in [v0.2.9](https://github.com/janeczku/rancher-letsencrypt/releases/tag/v0.2.9).

**Comment by yobasystems** [comment]
Thanks for this, much appreciated. I will take a peek later this evening.
I've literally just transferred some of my domains to Cloudflare for this very reason and also as it seems their DNS servers are pretty quick, [DNSPERF](http://www.dnsperf.com/) has some more info.

**Comment by janeczku** [comment]
@yobasystems CloudFlare is probably the better choice anyways because of the limitations imposed by Namecheap (slow DNS propagation, requirement to whitelist IP for API access). I would appreciate if you'd give it a try though.

**Comment by Flowman** [comment]
@janeczku have you seen that [xenolf/lego#180](https://github.com/xenolf/lego/issues/180) has been closed and implemented. So we can now progress this request.

**Comment by janeczku** [comment]
@Flowman thanks for the info. I'll try to add this sometime next week.
