### ISSUE TITLE
Let's Encrypt failure to start

### ISSUE THREAD

**Issue by nlhkh** [janeczku/rancher-letsencrypt#8]
I am beginning to see these error messages

```
April 4, 2016 8:31:41 AM GMT+7level=info msg="Starting Let's Encrypt Certificate Manager v0.2.5 a31b992"
April 4, 2016 8:31:51 AM GMT+7level=fatal msg="Rancher client: Get https://my.rancher.api.host/v1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
```

Before that `rancher-letsencrypt` has been working normally for me. What could be the reason for the error?

**Comment by janeczku** [comment]
Looks like a Rancher issue. It can't reach my.rancher.api.host. So either the private network isn't working at all or it's not available immediately on container start. You could troubleshoot by starting the container then immediatley get a shell and ping the Api host.
Meanwhile i have changed the code to make it retry the API connection when there is some error: https://github.com/janeczku/rancher-letsencrypt/commit/5dbb48c5374514806de8a694af0ee0693965bb4f

**Comment by nlhkh** [comment]
After leaving it for a while, everything is okay now. I guess it was networking issue with Rancher.

**Comment by janeczku** [comment]
Great! I am closing this.

**Comment by zhang8473** [comment]
I got the same problem. The rancher server was indeed reached because all of services are displayed under the stacks. However, no service starts and the status of all of them are "inactive". A bug in rancher?
