### ISSUE TITLE
Support DNSimple

### ISSUE THREAD

**Issue by ianwalter** [janeczku/rancher-letsencrypt#9]
Looks like work has already begun? I can help out on this but I would need some time because I'm new to Rancher.

**Comment by janeczku** [comment]
Support for DNSimple has already landed: https://github.com/janeczku/rancher-letsencrypt/commit/8d2b4cc8e0a5f7bb1a97f229d8b880d1a0a9c2d9
The PR to upgrade the community catalog image is waiting to be merged: https://github.com/rancher/community-catalog/pull/91
