### ISSUE TITLE
Where does the file get created in the container?

### ISSUE THREAD

**Issue by jeffreyces** [janeczku/rancher-letsencrypt#91]
Using version 5 at the moment.

I have been trying to figure out where the files get created. I am using HTTP verification and have been having issues trying to use NGINX and proxy_pass to the container but with no avail. I had it work for me once, but haven't been able to make it work since.

I'd like to be able to use -v to a folder in my webserver

Does anybody know where this location is?

**Comment by solocommand** [comment]
The certs are stored under `/etc/letsencrypt` inside the container.

**Comment by jeffreyces** [comment]
Actually, I was talking about the ./well-known/ folder, sorry I wasn't more accurate! But thanks anyways!

On a good note, I have successfully figured this problem out, I'll close this out.
